# Generated by Django 2.0.13 on 2020-04-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='ramp_colour',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='waiver',
            name='signatory_first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='waiver',
            name='signatory_last_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='waiver',
            name='signatory_signature',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='waiver',
            name='witness_first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='waiver',
            name='witness_last_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='waiver',
            name='witness_signature',
            field=models.CharField(default='', max_length=180),
        ),
    ]
